
import Header from '@/components/Header'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Wrapper from '@/components/Wrapper';
import Provider from '@/views/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shadcn UI Next App',
  description: 'Generated by create next app - shadcn ui',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Provider>
          <Header/>
        {
        children
        }
        <Footer/>
          </Provider>
      
        </Wrapper>
       
        </body>
    </html>
  )
}
